<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>thunderfield_wingman</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Fonts\MS33558C.otf" />
    <None Remove="thunderfield_banner.png" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Fonts\MS33558C.otf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\thunderfield_banner.png" />
  </ItemGroup>

</Project>
